# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='same',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
